// Hebrew UI strings. ערימה = discard pile, קופה = stock deck.
export const T = {
  appTitle: 'שִׁיטְהֶד',
  you: 'אתה',
  opponent: 'יריב',
  discard: 'ערימה',
  deck: 'קופה',
  play: 'שחק',
  takePile: 'קח ערימה',
  confirm: 'אשר',
  newGame: 'משחק חדש',
  playAgain: 'שחק שוב',
  confirmNewTitle: 'להתחיל משחק חדש?',
  confirmNewBody: 'המשחק הנוכחי יימחק.',
  yes: 'התחל',
  cancel: 'ביטול',
  thinking: 'הבוט חושב…',
  yourTurn: 'תורך',
  oppTurn: 'תור היריב',
  chooseFaceUp: 'בחר 3 קלפים גלויים',
  youWin: 'ניצחת! 🎉',
  youLose: 'הבוט ניצח',
  faceDownHint: 'הפוך קלף נסתר',
  willPlay: 'חוקי ✓',
  willPickup: 'לא חוקי — תיקח את הערימה',
} as const;
